
CREATE TABLE [dbo].[SmartHomeData](
	[Idx] [bigint] IDENTITY(1,1) NOT NULL,
	[DEV_ID] [varchar](10) NOT NULL,
	[CURR_DT] [datetime] NOT NULL,
	[TEMP] [float] NOT NULL,
	[HUMID] [float] NOT NULL,
 CONSTRAINT [PK_SmartHomeData] PRIMARY KEY CLUSTERED 
(
	[Idx] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


